language: ruby
rvm:
 - 2.5.5
 - jruby

# before_install:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"

dist: xenial
services:
  - xvfb
  - postgresql

before_script:
  - psql -c 'create database "kings_castle_test";' -U postgres